import { ModelConfig } from "./types";

export const hailuo02: ModelConfig = {
  id: "hailuo-02",
  name: "Hailuo-02",
  owner: "minimax",
  model: "hailuo-02",
  description:
    "High-quality video generation from text prompts with optional first and last frame control",
  category: "image-to-video",
  estimatedTime: "30-60 сек",
  quality: "high",
  schema: {
    required: ["prompt", "duration"],
    properties: {
      prompt: {
        type: "string",
        title: "Prompt",
        description: "Text prompt for generation",
        "x-order": 0,
        "x-component": "textarea",
        "x-grid-column": 1,
        "x-ui-field": "prompt",
        "x-api-field": "prompt",
      },
      first_frame_image: {
        type: "string",
        format: "uri",
        title: "First Frame Image",
        description:
          "First frame image for video generation. The output video will have the same aspect ratio as this image.",
        "x-order": 1,
        "x-component": "image-upload",
        "x-grid-column": 1,
        "x-ui-field": "firstFrameImage",
        "x-api-field": "first_frame_image",
      },
      last_frame_image: {
        type: "string",
        format: "uri",
        title: "Last Frame Image",
        description:
          "Last frame image for video generation. The final frame of the output video will match this image.",
        "x-order": 2,
        "x-component": "image-upload",
        "x-grid-column": 1,
        "x-ui-field": "lastFrameImage",
        "x-api-field": "last_frame_image",
      },
      duration: {
        type: "integer",
        title: "Duration",
        description:
          "Duration of the video in seconds. 10 seconds is only available for 768p resolution.",
        enum: [6, 10],
        default: 6,
        "x-order": 3,
        "x-component": "button-group",
        "x-grid-column": 2,
        "x-ui-field": "duration",
        "x-api-field": "duration",
      },
      resolution: {
        type: "string",
        title: "Resolution",
        description:
          "Pick between standard 512p, 768p, or pro 1080p resolution. The pro model is not just high resolution, it is also higher quality.",
        enum: ["512p", "768p", "1080p"],
        default: "1080p",
        "x-order": 4,
        "x-component": "button-group",
        "x-grid-column": 2,
        "x-ui-field": "resolution",
        "x-api-field": "resolution",
      },
      prompt_optimizer: {
        type: "boolean",
        title: "Prompt Optimizer",
        description: "Use prompt optimizer",
        default: true,
        "x-order": 5,
        "x-component": "toggle",
        "x-grid-column": 2,
        "x-ui-field": "promptOptimizer",
        "x-api-field": "prompt_optimizer",
      },
      seed: {
        type: "integer",
        title: "Seed",
        description: "Random seed for reproducible generation",
        "x-order": 6,
        "x-component": "number-input",
        "x-grid-column": 2,
        "x-ui-field": "seed",
        "x-api-field": "seed",
      },
    },
  },
  output: {
    type: "string",
    format: "uri",
    title: "Output",
  },
};
